apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
spec:
  type: ClusterIP
  selector:
    app: orders-service
  ports:
    - port: 3001
      targetPort: 3001
